{{- if and (not .Values.inventorymysql.enabled) (not .Values.mysqlURI) .Values.mysql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "inventory.fullname" . }}
  labels:
    {{- include "inventory.labels" . | indent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
{{- end }}