apiVersion: v1
kind: Service
metadata:
  name: {{ template "inventory.fullname" . }}
  labels:
    {{- include "inventory.labels" . | indent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: http
  selector:
    {{- include "inventory.labels" . | indent 4 }}