sudo: required
language: java
env:
  global:
    - jdbcURL=jdbc:mysql://mysql:3306/inventorydb?useSSL=false
    - dbuser=root
    - dbpassword=password
    - zipkinHost=localhost
    - zipkinPort=9411
    - IMAGE_NAME=inventory-mp
    - TAG=travis-latest
    - RELEASE_NAME=inv
stages:
  - local build and test
  - docker build, deploy, and test
  - kubernetes build, deploy, and test
jobs:
  include:
    - stage: local build and test
      services:
      - docker
      before_script:
      # Wait for MySQL to start, then load it with catalog data
      - docker run -p 9041:3306 -d --name mysql -e MYSQL_ROOT_PASSWORD=password ibmcase/bc-inventorydb:v2.0.0
      # Wait for MySQL to load data
      - sleep 25
      script:
      # Maven Build
      - mvn install
      # Start Application
      - mvn liberty:start-server -DtestServerHttpPort=9081
      # Wait for the Inventory container to start accepting connections
      - sleep 25
      # Run Catalog API Test
      - bash scripts/api_tests.sh 127.0.0.1 9081
    - stage: docker build, deploy, and test
      services:
      - docker
      install:
        - true
      before_script:
      # Wait for MySQL to start, then load it with catalog data
      - docker run -p 9041:3306 -d --name mysql -e MYSQL_ROOT_PASSWORD=password ibmcase/bc-inventorydb:v2.0.0
      # Wait for MySQL to load data
      - sleep 25
      script:
      # Maven Build
      - mvn install
      # Build Docker image
      - docker build -t "${IMAGE_NAME}:${TAG}" .
      # Start Inventory Container and Connect to local MySQL Service
      - docker run -d -p 9081:9080 --name inventory -t --link mysql:mysql --env jdbcURL=jdbc:mysql://mysql:3306/inventorydb?useSSL=false --env dbuser=root --env dbpassword=password --env zipkinHost=localhost --env zipkinPort=9411 "${IMAGE_NAME}:${TAG}"
      # Wait for the Inventory container to start accepting connections
      - sleep 25
      # Check that the Inventory container is running
      - docker ps
      # Check logs to see if it started properly
      - docker logs inventory
      # Run Inventory API Test
      - bash scripts/api_tests.sh 127.0.0.1 9081
    - stage: kubernetes build, deploy, and test
      services:
      - docker
      env:
      - CHANGE_MINIKUBE_NONE_USER=true
      before_install:
      # install nsenter for helm and port forwarding
      - sudo apt-get -qq update
      - sudo apt-get install -y socat
      - docker run --rm jpetazzo/nsenter cat /nsenter > /tmp/nsenter && chmod +x /tmp/nsenter
      - sudo cp /tmp/nsenter /usr/local/bin
      install:
        - true
      before_script:
      # Install nsenter, which is needed for minikube to work
      - bash scripts/install_minikube_and_helm.sh
      # Install MySQL
      - helm install --name mysql ./chart/inventorydb
      script:
      # Build Docker image
      - docker build -t "${IMAGE_NAME}:${TAG}" .
      # Install Inventory
      - helm install --set travis=true --name inv ./chart/inventory
      # Wait for Inventory to be ready
      - kubectl get deployments ${RELEASE_NAME}-inventory -o yaml
      - READY=$(kubectl get deployments ${RELEASE_NAME}-inventory -o yaml | grep "readyReplicas" | awk '{print $2}')
      - echo $READY
      - until [ -n "$READY" ] && [ ${READY} -ge 1 ]; do READY=$(kubectl get deployments ${RELEASE_NAME}-inventory -o yaml | grep "readyReplicas" | awk '{print $2}'); kubectl get deployments -o wide; echo "Waiting for inventory to be ready"; sleep 10; done
      # Wait for Inventory deployment to start accepting connections
      - sleep 35
      # Run Inventory API Test
      - MINIKUBE_IP=$(minikube ip)
      - NODE_PORT=$(kubectl get service ${RELEASE_NAME}-inventory -o=jsonpath='{.spec.ports[0].nodePort}')
      - bash scripts/api_tests.sh $MINIKUBE_IP $NODE_PORT
