apiVersion: batch/v1
kind: Job
metadata:
  name: micro-inventory-populate-mysql
spec:
  template:
    metadata:
      name: micro-inventory-populate-mysql
      labels:
        app: micro-inventory
    spec:
      restartPolicy: Never
      initContainers:
      - name: test-mysql
        image: mysql:5.7.14
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        - "-c"
        - "until mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e status; do echo waiting for mysql; sleep 1; done"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "inventorydb"
          - name: MYSQL_USER
            value: "dbuser"
          - name: MYSQL_PASSWORD
            value: "password"
      containers:
      - name: populate-mysql
        image: mysql:5.7.14
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /db-data
          name: db-data
        command: ["/bin/bash", "-c"]
        args: ["cp /config/mysql_data.sql /db-data; sed -i \"s/inventorydb/${MYSQL_DATABASE}/g\" /db-data/mysql_data.sql; until mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} </db-data/mysql_data.sql; do echo \"waiting for mysql\"; sleep 1; done; echo \"Loaded data into database\";"]
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "inventorydb"
          - name: MYSQL_USER
            value: "dbuser"
          - name: MYSQL_PASSWORD
            value: "password"
      volumes:
      - name: config
        configMap:
          name: micro-inventory-data
      - name: db-data
        emptyDir:
          medium: "Memory"
