{{- if .Values.dataloader.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ cat .Release.Name "-" .Chart.Name "-populate-mysql-" (randAlphaNum 5 | lower) | nospace | trunc 63 }}
  labels:
    {{- include "inventory.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ cat .Release.Name "-" .Chart.Name "-populate-mysql-" (randAlphaNum 5 | lower) | nospace }}
      labels:
        {{- include "inventory.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      initContainers:
      {{- include "inventory.mysql.initcontainer" . | indent 6 }}
      containers:
      - name: populate-mysql
        image: {{ .Values.dataloader.image.repository }}:{{ .Values.dataloader.image.tag }}
        imagePullPolicy: {{ .Values.dataloader.image.pullPolicy }}
        env:
        {{- include "inventory.mysql.environmentvariables" . | indent 8 }}
{{- end }}