replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  tag: 0.5.0
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  nodePort: 32380

ingress:
  enabled: false
  hostname: inventory.bluecompute.com
  path: /micro/inventory
  ibmCloud:
    redirectToHTTPS: false

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

mysql:
  host: inventory-mysql
  port: 3306
  existingSecret:
  user: dbuser
  password: password
  database: inventorydb
  # For mysql init container
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: IfNotPresent

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi

labels:
  app: inventory
  version: v1
  tier: backend

istio:
  enabled: false
  # ISTIO_MUTUAL, SIMPLE, DISABLE
  mTLS: ISTIO_MUTUAL
  # LEAST_CONN, ROUND_ROBIN
  loadBalancer: LEAST_CONN
  enableGateway: false
  httpsRedirect: false
  hosts:

global:
  istio:
    enabled: