apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: micro-inventory-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-inventory
    spec:
      containers:
      - name: inventory
        image: ibmcase/bluecompute-inventory:0.6.0
        imagePullPolicy: Always
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "inventorydb"
          - name: MYSQL_USER
            value: "dbuser"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: SERVICE_PORT
            value: "8080"
