replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  pullPolicy: Always
  tag: latest

service:
  name: inventory
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

ingress:
  enabled: false
  hostname: inventory.bluecompute.com
  path: /micro/inventory

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

# Source for dataloader found in:
# https://github.com/ibm-cloud-architecture/refarch-cloudnative-devops-kubernetes/tree/master/docker_images/mysql-loader
dataloader:
  enabled: true
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest
    pullPolicy: Always

# External MySQL Deployment
# This is just for quick testing and it exposes the password
# mysql://dbuser:password@mysql-host:3306/inventorydb
mysqlURI: 

# External MySQL Deployment
mysql:
  host: mysql-host
  port: 3306
  user: dbuser
  password: password
  database: inventorydb

# Included Community MySQL Chart
inventorymysql:
  enabled: false
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: IfNotPresent
  fullnameOverride: bluecompute-inventory-mysql
  mysqlRootPassword: admin123
  mysqlUser: dbuser
  mysqlPassword: password
  mysqlDatabase: inventorydb
  service:
    port: 3306
  persistence:
    enabled: false

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi